### ISSUE TITLE
npm build command mishandling?

### ISSUE THREAD

**Issue by brianzelip** [johnotander/css-properties#4]
Cloned this to check for any updates to the w3schools list of properties, noticed running `npm build` from #3 didn't actually recreate the json file.

It might be due to outdated node version, so clone it into a temporary directory, delete the json file then run the command to see for yourself.

If it is a bug and not outdated node, I think it's because `npm build` is a [special command](https://docs.npmjs.com/cli/build).

A few options to fix:
1. Change package.json script from `"build": "node build",` to `"start": "node build",` or
2. Tell folks in the docs to run `node build` or `npm run-script build`

@blakeembrey's [build command](https://github.com/blakeembrey/language-map/blob/master/package.json#L7-L8) works a little differently since he's pointing to a build file.

**Comment by johnotander** [comment]
Thanks for reporting!

Yeah, I think documentation needs to be added to specify `$ npm run build` rather than `$ npm build` to get the desired results, I've been able to verify that the results are correct with `$ npm run build`:

```sh
~/code/css-properties master
❯ rm w3c-css-properties.json 

~/code/css-properties master*
❯ g?
 D w3c-css-properties.json

~/code/css-properties master*
❯ npm run build

> css-properties@2.0.2 build /Users/johno/code/css-properties
> node build


~/code/css-properties master
❯ g?

~/code/css-properties master
❯ node -v
v5.3.0

~/code/css-properties master
❯ npm -v
3.5.2
```
